version: 2
updates:
  - package-ecosystem: "pnpm" 
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    target-branch: "develop"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5